<a href="https://colab.research.google.com/github/VishalDalwadi/027_VishalDalwadi/blob/main/Lab_01_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [4]:
import numpy as np
import pandas as pd

In [5]:
# initialize matrices
array1 = np.array([[1, 2, 3],[4, 5, 6]])
array2 = np.array([[7, 10],[8, 11],[9, 12]])
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]]
[[ 7 10]
 [ 8 11]
 [ 9 12]]


In [6]:
#randomly initialize array
array = np.random.rand(3, 4)
print(array)

[[0.13307127 0.24418718 0.02285162 0.84067265]
 [0.32896992 0.21523318 0.5133984  0.16234388]
 [0.16044939 0.21550277 0.35613553 0.78385705]]


In [7]:
# matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[ 50  68]
 [122 167]]


In [8]:
# element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res) 

[[50, 68], [122, 167]]


In [9]:
# first matrix mean
mean = np.mean(array1)
print(mean)

3.5


In [11]:
main_data = pd.read_csv("/content/drive/MyDrive/ML/Lab1/mtcars.csv")

In [ ]:
del main_data['model']
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())


        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
